lang/erlang-runtime25: update to version 25.2.1
freebsd/freebsd-ports pull request #146
Opened 2023-01-23 18:34 UTC by sax

2023-01-23 18:41 UTC, sax commented
This successfully builds, and I've successfully run elixir 1.14.3 using the resulting package. I still need to build all the packages that depend on lang/erlang to verify that they work against these changes.

2023-01-25 03:17 UTC, sax commented
I see the following ports effecting by these changes:

```
$ pkg rquery %ro lang/erlang-runtime25
databases/couchdb3
```

```
$ pkg rquery %ro lang/erlang-runtime24
net/rabbitmq
```

```
$ pkg rquery %ro lang/erlang
net-im/ejabberd
lang/elixir
lang/erlang-wx
devel/erlang-recon
lang/erlang-java
devel/erlang-cl
devel/erlang-rebar3_hex
lang/lfe
devel/rebar
devel/rebar3
benchmarks/tsung
graphics/wings
www/yaws
```

I'm in the process of building them all, but it will be a little while until it's completed. So far so good!

2023-01-25 12:59 UTC, dch requested changes
LGTM, fix the portepoch, and pending poudriere test, let's ship it.

2023-01-25 12:59 UTC, dch commented on lang/erlang/Makefile
> -PORTEPOCH=	4
if we have an EPOCH, [it needs to be preserved](https://docs.freebsd.org/en/books/porters-handbook/book/#makefile-naming-revepoch)

2023-01-25 12:59 UTC, dch commented on lang/erlang/Makefile
> +CHUNKS_MAKE_ARGS+=		docs DOC_TARGETS=chunks
no need to change this, unless `portfmt -t -i Makefile` disagrees *and* doesn't break thiings.

2023-01-25 17:20 UTC, sax commented on lang/erlang/Makefile
> -PORTEPOCH=	4
Oh! I think I saw those docs earlier, but misread them as applying to the DISTVERSION. I just pushed a commit that brings it back.

2023-01-25 17:21 UTC, sax commented on lang/erlang/Makefile
> +CHUNKS_MAKE_ARGS+=		docs DOC_TARGETS=chunks
Ok, sounds good. I saw this change in `lang/erlang-runtime25` and applied it, but it makes sense to me to keep this changeset as minimal as possible.

2023-01-25 19:43 UTC, dch commented
thanks @sax, committed along with:

commit c9033971719dc098b34276f11b8e5a5e22b966fd
Author: Dave Cottlehuber <dch@FreeBSD.org>
Date:   Wed Jan 25 19:42:29 2023 +0000

    net/rabbitmq: update to 3.11.7 & switch to OTP25

    - while here, pet with portfmt and portclippy

commit 8893a5541856e22a2518b4ded2a8797d0c8974e0
Author: Dave Cottlehuber <dch@FreeBSD.org>
Date:   Wed Jan 25 19:42:29 2023 +0000

    lang/elixir-devel: update to 1.14.3

commit 1fd735a7234415ee15c7db3ee8b1e170945d35a4
Author: Dave Cottlehuber <dch@FreeBSD.org>
Date:   Wed Jan 25 19:42:29 2023 +0000

    databases/couchdb3: bump after lang/erlang-runtime25

commit 52ef12461ce4facd23d79794a2015500170adb3d
Author: Eric Saxby <sax@livinginthepast.org>
Date:   Wed Jan 25 19:42:29 2023 +0000

    lang/erlang-runtime25: update to version 25.2.1

commit 0e6053dc8839f9a90153cb42fe8a9755c27cf1e3
Author: Eric Saxby <sax@livinginthepast.org>
Date:   Wed Jan 25 19:42:28 2023 +0000

    lang/erlang-runtime24: update to 24.3.4.8

commit 428d54e3d199c8f6eed319becc6f58fa4c1798c8
Author: Eric Saxby <sax@livinginthepast.org>
Date:   Wed Jan 25 19:42:28 2023 +0000

    lang/erlang: update to version 25.2.1

2023-01-25 19:43 UTC, closed without merging