sysutils/tt: New port
freebsd/freebsd-ports pull request #232
Opened 2024-02-08 18:28 UTC by 0x501D

Command-line utility to manage Tarantool applications.

2024-02-08 18:52 UTC, arrowd commented
@wahjava You're knowledgeable in Go, would mind looking at this?

2024-02-09 04:42 UTC, metalefty commented on sysutils/tt/Makefile
> +GH_TUPLE=	\
Now we can use GO_MODULE instead of GH_TUPLE.

2024-02-10 10:36 UTC, wahjava requested changes

2024-02-10 10:36 UTC, wahjava commented on sysutils/tt/Makefile
> +GH_TUPLE=	\
Yep, it'll also help with fetching modules which aren't on GitHub.

2024-02-13 08:25 UTC, 0x501D commented on sysutils/tt/Makefile
> +GH_TUPLE=	\
Unfortunately, tt does not work as a go module due to the complexity and structure of the project itself:
```sh
$ go get github.com/tarantool/tt@latest
go: github.com/tarantool/cartridge-cli@v0.0.0-20220605082730-53e6a5be9a61 (replaced by ./cli/cartridge/third_party/cartridge-cli): reading cli/cartridge/third_party/cartridge-cli/go.mod: open /home/void/tmp/cli/cartridge/third_party/cartridge-cli/go.mod: no such file or directory
```

2024-02-13 12:09 UTC, 0x501D commented on sysutils/tt/Makefile
> +GH_TUPLE=	\
Is it possible to just remove `USES= go:modules`, GH_TUPLE and just do the mage build in the Makefile?

2024-02-13 12:19 UTC, 0x501D commented on sysutils/tt/Makefile
> +GH_TUPLE=	\
And if port absolutely need to build without a network, I can try to use a cache of vendor libraries, the `tt` repository has them for `tt` gentoo ebuild.

2024-05-31 08:09 UTC, closed without merging