x11/gbsddialog: add new port
freebsd/freebsd-ports pull request #235
Opened 2024-02-17 22:15 UTC by khorben

gbsddialog is an implementation of bsddialog, a text-based user interface to be used in scripts and tools, such as in the official FreeBSD installer, bsdinstall(8). gbsddialog uses Gtk+ dialogs and widgets instead of console-based equivalents. The objective is to reproduce the same behaviour as the original tool, respecting the exact command-line parameters and output. gbsddialog can then be used as a drop-in replacement to bsddialog, effectively granting the possibility to install and configure FreeBSD entirely in graphical mode.

In addition, an implementation of Xdialog is also provided, for use with bsdconfig(8) when invoked in graphical mode with -S or -X.

Sponsored by: The FreeBSD Foundation

2024-02-18 03:31 UTC, Jehops requested changes
Looks good other than a few minor nits.

2024-02-18 03:31 UTC, Jehops commented on x11/gbsddialog/Makefile
> +MAKE_ARGS+=	MANDIR=${PREFIX}/man
We're standardizing the installation of man pages to `share/man`.    Could you install them there?

2024-02-18 03:31 UTC, Jehops commented on x11/gbsddialog/pkg-plist
> +%%PORTDOCS%%%%DOCSDIR%%/samples/Xdialog.wrapper.c
I thnk you're missing `%%PORTDOCS%%%%DOCSDIR%%/COPYING`.

2024-02-18 03:31 UTC, Jehops commented on x11/gbsddialog/Makefile
> +CONFLICTS_INSTALL=	xdialog-*
This should go above `OPTIONS_DEFINE`.

2024-02-18 03:31 UTC, Jehops commented on x11/gbsddialog/Makefile
> +USE_GNOME=	gtk30 pango cairo gdkpixbuf2 glib20
Could you sort these?
```
USES=		gettext-runtime gnome pkgconfig
USE_GNOME=	cairo gdkpixbuf2 glib20 gtk30 pango
```
 `portclippy` and `portfmt` from `ports-mgmt/portfmt` are helpful for these sorts of things.

2024-02-19 13:42 UTC, khorben commented on x11/gbsddialog/pkg-plist
> +%%PORTDOCS%%%%DOCSDIR%%/samples/Xdialog.wrapper.c
> I thnk you're missing `%%PORTDOCS%%%%DOCSDIR%%/COPYING`.

Isn't it already automatically copied as `/usr/local/share/licenses/gbsddialog-0.8.1/BSD2CLAUSE`?

2024-02-20 01:56 UTC, Jehops commented on x11/gbsddialog/pkg-plist
> +%%PORTDOCS%%%%DOCSDIR%%/samples/Xdialog.wrapper.c
You still have to account for it, otherwise, Q/A tests will fail.

```
===========================================================================
====> Running Q/A tests (stage-qa)
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%PORTDOCS%%%%DOCSDIR%%/COPYING
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1
```

2024-02-20 16:57 UTC, khorben commented on x11/gbsddialog/pkg-plist
> +%%PORTDOCS%%%%DOCSDIR%%/samples/Xdialog.wrapper.c
Strange, I have been running `make stage-qa` both with and without the `DOCS` option, and this warning never triggered.
Should I also change the line for `README.md` to be in `%%PORTDOCS%%%%DOCSDIR%%`?

2024-02-20 22:36 UTC, Jehops commented on x11/gbsddialog/pkg-plist
> +%%PORTDOCS%%%%DOCSDIR%%/samples/Xdialog.wrapper.c
I think the entries for both `README.md` and `COPYING` could be
```
%%PORTDOCS%%%%DOCSDIR%%/COPYING
%%PORTDOCS%%%%DOCSDIR%%/README.md
```
That is what most other ports are doing.
```
% rg --no-heading -Ig "*/*/pkg-plist" "%%DOCSDIR%%/COPYING" | wc -l
     232
% rg --no-heading -Ig "*/*/pkg-plist" "%%PORTDOCS%%%%DOCSDIR%%/COPYING" | wc -l
     202

% rg --no-heading -Ig "*/*/pkg-plist" "%%DOCSDIR%%/README" | wc -l
    1727
% rg --no-heading -Ig "*/*/pkg-plist" "%%PORTDOCS%%%%DOCSDIR%%/README" | wc -l
    1576
```

2024-02-21 04:26 UTC, Jehops commented
Committed.  Thanks.

https://cgit.freebsd.org/ports/commit/?id=7b0bec15a69a325190b01f433cb506f1cb004df2

2024-03-22 19:25 UTC, closed without merging