The Ports Collection is now git-based
freebsd/freebsd-ports pull request #250
Opened 2024-04-23 03:40 UTC by motminh

Pull requests are accepted at https://github.com/freebsd/freebsd-ports

2024-06-20 21:51 UTC, concussious requested changes

2024-06-20 21:51 UTC, concussious commented on CONTRIBUTING.md
> +FreeBSD does accept pull requests.
```suggestion
FreeBSD Ports changes can be proposed via patches submitted to Bugzilla, Differential Revisions on Phabricator, or Pull Requests on Github.
```

Although, I haven't heard anything from the ports team to suggest that they are switching their preference.

2024-06-20 22:32 UTC, yurivict commented
I don't think that this is an acceptable change.

Let's say I maintain the port x/y. Someone would submit a pull request.
How would I be notified about this PR and other PRs for my ports?
Is there a mechanism of notification?
Is there a mechanism for port committers to merge/reject GitHub PRs?

2024-06-20 22:53 UTC, bsdimp commented
Right now the volume  is low enough it can be done manually. But we make no qos on these requests, and don't count it toward timeouts.

But if you want automation join my hithub working group. That's the right answer long term.

2024-06-20 22:54 UTC, bsdimp commented on CONTRIBUTING.md
> +FreeBSD does accept pull requests.
I'd make sure that people know of the still experimental nature of prs.

2024-06-21 01:54 UTC, concussious commented on CONTRIBUTING.md
> +FreeBSD does accept pull requests.
1 may I join working group?
2 suggestion edited.

2024-06-21 11:48 UTC, concussious commented on CONTRIBUTING.md
>  Please see the [Porter's Handbook](https://docs.freebsd.org/en/books/porters-handbook/) section on [Submitting patches](https://docs.freebsd.org/en/books/porters-handbook/quick-porting/#porting-submi
```suggestion
# FreeBSD Ports Collection Contribution Guidelines
The FreeBSD Ports Collection prefers code contributions using either:
- A code review in [Phabricator](https://reviews.freebsd.org/differential)
- An attachment on a [Bugzilla ticket](https://bugs.freebsd.org)
GitHub Pull Requests are an experimental feature and should expect additional delay.

To learn more about contributing to the FreeBSD Ports Collection, please see the [Porter's Handbook](https://docs.freebsd.org/en/books/porters-handbook/) section on [Submitting patches](https://docs.freebsd.org/en/books/porters-handbook/quick-porting/#porting-submitting).
```

2024-08-22 17:23 UTC, diizzyy commented
I'd argue that we shouldn't accept PRs at all, no one looks at this regulary (that commits) and given that it's not covered by Porters Handbook we're just going to suggest people to submit it bugzilla instead anyway.

2024-08-22 20:58 UTC, concussious commented
This is a feature that we have, PR is just updating the doc to reflect that.

All it takes is someone to start, but beloved ports team is currently doing an unprecedented amount of work per person according to the presentation at nycbug. If I'm understanding policy correctly it's a "when" not an "if", and the language I suggested reflects that.

2024-09-01 21:54 UTC, concussious commented on CONTRIBUTING.md
>  Please see the [Porter's Handbook](https://docs.freebsd.org/en/books/porters-handbook/) section on [Submitting patches](https://docs.freebsd.org/en/books/porters-handbook/quick-porting/#porting-submi
TIL more about this issue and edited my suggestion above. One thumbs up emoji appeared before today's edit and does not reflect the new suggestion.

2025-02-03 20:34 UTC, concussious commented
I committed the above suggestion in d90070c244c07d1c365d9f9dd498a68ee1ea5314 , this can be closed.

2025-02-05 00:09 UTC, metalefty commented
ref. https://reviews.freebsd.org/D47169

2025-02-05 00:09 UTC, closed without merging