Add new category fs for file systems
freebsd/freebsd-ports pull request #302
Opened 2024-09-29 01:05 UTC by clausecker

This patch set adds a new category *fs* for file systems and file system utilities.  The new category is populated with some 126 ports (that's more than *x11-clocks*!) that look like they might be file-system related.

I was motivated to add this new category when I noticed that many FUSE file systems were shipped as ports named sysutils/fusefs-$foo, making *sysutils/fusefs-* a pseudo-category for FUSE filesystems.  If that's the (anti) pattern, why not make it offical and add a true category for file system ports?  Turns out there are a lot more than one might think.

I hope that with this move, we can reduce the load on *devel* and *sysutils* (the two most popular misspellings of *misc*) and make file-system related ports easier to find.

For a full list of affected ports, see the list of commits attached to this PR.  If you would like to not have your port moved to *fs*, please comment or send me an email.

2024-09-30 00:30 UTC, metalefty commented
I personally like that idea. That sounds reasonable because there are more ports than x11-clocks. BTW, I like filesystem(s) more than fs.

2024-09-30 07:18 UTC, rosorio commented
Hi',El 30 sept 2024 2:30, metalefty ***@***.***> escribió:
I personally like that idea. That sounds reasonable because there are more ports than x11-clocks. BTW, I like filesystem(s) more than fs.Same opinion  +1Rodrigo

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2024-10-02 15:42 UTC, Jehops commented
Robert, as we discussed in Dublin, I generally think creating a new `fs` category for filesystems is a good idea.  However, I'm on the fence about moving _utilities_ such as `sysutils/zrepl` or `sysutils/zfs-snapshot-mgmt`.  If others agree that also moving those ports is beneficial, then we should make it clear in the comment in `fs/Makefile` that utilities related to filesystems also belong there.

Here are a few more for you:

1.
```
commit 230cb49ccce5a79985875ad16e36da0b8f9e8c52
Author:     Emanuel Haupt <ehaupt@FreeBSD.org>
AuthorDate: 2024-10-02 07:52:13 +0000
Commit:     Emanuel Haupt <ehaupt@FreeBSD.org>
CommitDate: 2024-10-02 07:52:32 +0000

    sysutils/fusefs-mergerfs: Add new port
    
    mergerfs is a union filesystem geared towards simplifying storage and
    management of files across numerous commodity storage devices. It is
    similar to mhddfs, unionfs, and aufs.
```
2. (If we decide fs utilities should also be moved)
```
% cat sysutils/zap/pkg-descr
Maintain and replicate ZFS snapshots

zap automates the management of zfs snapshots.  With a few, simple
crontab entries, it can be used to create a comprehensive zfs backup
system.  There are no configuration files.  All parameters are supplied
on the command line or in zfs properties and all snapshot information
is stored in snapshot names.

zap plays nice with manually created snapshots or snapshots from other
tools.  It will only operate on snapshots it creates.
```

2024-10-02 16:20 UTC, clausecker commented
@jehops Thank you for your concerns.

The current comment was supposed to read:

    COMMENT = File systems and utilities

but I must have dropped the second half during copy editing.  I'll restore that in my next push.  I am open to having a category for only file system drivers, but I would prefer to also put the fs utilities in there.  We could also add two categories: one for file system drivers and one for associated utilities (e.g. `fsutil` or `fs-mgmt`).

I'll go add the other two ports, too.

2024-10-02 17:18 UTC, Jehops commented
> ```
> COMMENT = File systems and utilities
> ```
Taking inspiration from existing comments, how about `File systems and related utilities`? 

```
games/Makefile    COMMENT = Games and related software
databases/Makefile    COMMENT = Databases and related software
finance/Makefile    COMMENT = Monetary, financial, and related applications
```

2024-10-02 18:51 UTC, clausecker commented
@jehops Yeah sure, works for me.  I'll put that in with my next edit.

2024-10-06 12:50 UTC, diizzyy commented
Why this is submitted to GitHub? It's not a supported way of submitting patches (see Porters Handbook). Submit it to bugzilla and continue the discussion there.

2024-10-06 13:38 UTC, bsdimp commented
@diizzyy Other than "the rules" is there some good reason not do it here? It seems to have generated a reasonable amount of feedback so far.

2024-10-06 16:57 UTC, diizzyy commented
@bsdimp A lot more eyes and participants on bugzilla (and indirectly mailing lists), there's little to no involvement/interraction with most of the community including committers etc on GitHub.

2024-10-06 22:10 UTC, bsdimp commented
@diizzyy And bugzilla is the worst tool ever to review changes (even worse than phabricator). It's barely adequate as a conveyer belt for submissions. Github is much better, and can as easily be references in other forum as bugzilla. The current bugzilla workflow is unustainable, imho, and requires too much extra work. fuz's changes likely need detailed commentary, for which bugzilla is ill suited to do on a change this large. It can't handle 10 commits in one go, let alone 140. Since it is an imperfect fit, fuz will also need to seek review elsewhere (which I thought I'd seen an email go by that did), true, but going to bugzilla is setting him up to fail because it would be such a bad tool for a change like this.

2024-10-06 23:27 UTC, yurivict commented
> And bugzilla is the worst tool ever to review changes [...]

This is off-topic here, but you probably have never seen Jira that is used by many companies.
Compared to Jira, Bugzilla is a totally sane and pleasant tool.

--------------------------------------------

The key to your submission is not the exact list of ports, but the portmgr approval.
You need to contact somebody in the portmgr team and ask for approval.

Here is my proposal for the physics and chemistry categories from 2018 which is still not approved: https://reviews.freebsd.org/D13481

The FreeBSD Portmgr is a bit slow, don't you think?

2024-10-06 23:55 UTC, clausecker commented
@yurivict My original email went to ports@ as well as portmgr@ and explicitly asked for approval.  I hope that suffices.  If not, I'll bug portmgr some more (I encourage you to do the same about your proposal).

2024-10-09 18:30 UTC, diizzyy commented
@bsdimp 
Your personal preferrence is another topic as Yuri pointed out. The main issue is that this isn't a supported way of doing submissions, notifying people etc.

2024-10-10 01:56 UTC, bsdimp commented
> @bsdimp Your personal preferrence is another topic as Yuri pointed out. The main issue is that this isn't a supported way of doing submissions, notifying people etc.

Yes. And that's a problem too. The ossified FreeBSD processes aren't helpung the project.

2024-10-10 13:12 UTC, clausecker commented
I have just requesed an exp-run on Bugzilla: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281988

2024-10-18 12:18 UTC, mat813 commented
Please rename the category from `fs` to `filesystems`

2024-10-18 13:59 UTC, clausecker commented
@mat813 That's really quite a mouthful.  Should we also rename `sysutils` to `system-utilities`?  Or `devel` to `development`?  I would like to avoid such a long category name.  FS is a well known and unambiguous acronym, so I think it's fine as a category name.

2024-10-18 19:16 UTC, diizzyy commented
As much as fs is likely to be obvious for advanced users have really short acronyms can also cause unnecessary confusion.
OpenWrt for example also uses the full name, https://github.com/openwrt/packages/blob/master/utils/exfatprogs/Makefile#L24

2024-10-19 14:16 UTC, dlangille commented
I too prefer filesystems over fs.

2024-10-19 20:24 UTC, Jehops commented
I argue that using `fs` to describe the category follows precedence more than `filesystems`. 

The closest word to `file systems` in an existing category is `windows managers`, and we use `wm` for that category.   Using `fs` to describe a file system is so common it's in the first sentence of [the File Systems Wikipedia page](https://en.wikipedia.org/wiki/File_system).

2024-10-19 20:25 UTC, dlangille commented
> I argue that using `fs` to describe the category follows precedence more than `filesystems`.
> 
> The closest word to `file systems` in an existing category is `windows managers`, and we use `wm` for that category. Using `fs` to describe a file system is so common it's in the first sentence of [the File Systems Wikipedia page](https://en.wikipedia.org/wiki/File_system).

I concede.

2024-10-19 21:57 UTC, clausecker commented
@mat813 @Jehops @dlangille So, what do we do about this one?  Typing out filesystems makes me sad...

2024-10-20 09:14 UTC, mat813 commented
Please name the category filesystems.

2024-10-20 09:33 UTC, diizzyy commented
> I argue that using `fs` to describe the category follows precedence more than `filesystems`.
> 
> The closest word to `file systems` in an existing category is `windows managers`, and we use `wm` for that category. Using `fs` to describe a file system is so common it's in the first sentence of [the File Systems Wikipedia page](https://en.wikipedia.org/wiki/File_system).

That being said, wm is prefixed with x11-wm for clarity

2024-10-22 09:04 UTC, mat813 requested changes

2024-10-22 09:04 UTC, mat813 commented on misc/e2fsprogs-libblkid/Makefile
> +MASTERDIR=	${.CURDIR}/../../filesystems/e2fsprogs-core
I feel this should probably be moved to filesystems too.

2024-10-22 09:04 UTC, mat813 commented on misc/e2fsprogs-libuuid/Makefile
> +MASTERDIR=	${.CURDIR}/../../filesystems/e2fsprogs-core
I feel this should probably be moved to filesystems too.

2024-10-22 09:04 UTC, mat813 commented on security/vuxml/vuln/2011.xml
> +    <topic>filesystems/cfs -- buffer overflow</topic>
Historical data, please revert.

2024-10-22 09:04 UTC, mat813 commented on security/vuxml/vuln/2020.xml
> +    <topic>filesystems/openzfs-kmod -- critical permissions issues</topic>
Historical data, please revert.

2024-10-22 09:04 UTC, mat813 commented on sysutils/automount/Makefile
>  NTFS3G_DESC=		Enable NTFS write support with ntfs-3g over FUSE
It should probably be moved to filesystems too, or at least get the category.

2024-10-22 09:04 UTC, mat813 commented on sysutils/dsbmd/Makefile
>  PTP_DESC=	Picture Transfer Protocol support
It should probably be moved to filesystems too, or at least get the category.

2024-10-22 11:44 UTC, clausecker commented on Mk/bsd.port.mk
> +	filesystems games geography german gnome gnustep graphics \
Should each category be a line on its own or should only `filesystems` be a line on its own?

2024-10-22 11:47 UTC, clausecker commented on filesystems/webdavfs/Makefile
> +PKGNAMEPREFIX=	fusefs-
This is the same change that takes place for all `fusefs-...` ports to keep us from repeating `fusefs-` all over the place in the ports tree while keeping the package name the same.  Why do you want me to revert the change for this port only?

2024-10-22 11:49 UTC, clausecker commented on filesystems/ext2/Makefile
> +PKGNAMEPREFIX=	fusefs-
This is the same change as for all the other fuse file systems: fusefs- is removed from the port name and turned into a prefix to the package name.  Also note that the name already doesn't agree with upstream (fuse-ext2 vs. fusefs-ext2).  Are you sure you want me to make this one port inconsistent with the others?

2024-10-22 12:23 UTC, clausecker commented on misc/e2fsprogs-libuuid/Makefile
> +MASTERDIR=	${.CURDIR}/../../filesystems/e2fsprogs-core
I had decided against moving this port in particular as it's not really about file systems, but rather just about UUID generation.

2024-10-22 12:46 UTC, clausecker commented on misc/e2fsprogs-libblkid/Makefile
> +MASTERDIR=	${.CURDIR}/../../filesystems/e2fsprogs-core
Moved to filesystems as requested.

2024-10-22 12:47 UTC, clausecker commented on sysutils/dsbmd/Makefile
>  PTP_DESC=	Picture Transfer Protocol support
Moved to filesystems as requested.

2024-10-22 13:16 UTC, mat813 commented on Mk/bsd.port.mk
> +	filesystems games geography german gnome gnustep graphics \
It's mostly one line per letter

2024-10-22 13:17 UTC, mat813 commented on filesystems/ext2/Makefile
> +PKGNAMEPREFIX=	fusefs-
Please, keep the changes to a minimum, you are doing a sweeping commit for the category change, not fixing individual ports for other cosmetic changes.

2024-10-22 13:18 UTC, mat813 commented on filesystems/ntfs/files/patch-configure
> +-		as_fn_error $? "Please see FreeBSD support at http://www.freshports.org/filesystems/ntfs" "$LINENO" 5
The patch-configure patch is removing lines, if you change the lines it removes, it won't match, and fail.

2024-10-22 13:18 UTC, mat813 commented on filesystems/webdavfs/Makefile
> +PKGNAMEPREFIX=	fusefs-
Same answer, keep changes to a minimum

2024-10-22 13:31 UTC, clausecker commented on filesystems/ext2/Makefile
> +PKGNAMEPREFIX=	fusefs-
Ok, I will submit these two changes separately, even though it makes no sense.

2024-10-22 14:09 UTC, clausecker commented on Mk/bsd.port.mk
> +	filesystems games geography german gnome gnustep graphics \
Moved to its own line as requested.

2024-10-29 14:36 UTC, clausecker commented
Rebased onto ab6304e314b6d17d5103606e138cf4b9d2a6e24b.

2024-10-30 09:24 UTC, mat813 commented
Can you request an exp-run so we make sure everything is squared away, and if it comes back without problems and nothing new comes up here, feel free to commit it.

2024-10-30 13:09 UTC, mat813 commented
Oh, before you land this, please squash it all into a single commit.

2024-10-30 13:39 UTC, clausecker commented
@mat813 Are you sure?  I specifically made it a bunch of individual commits so it's easy to move individual ports back if desired.  Note that each of the commits is self-contained.

2024-10-30 14:02 UTC, mat813 commented
Please squash it all.
Also, make sure the tree is not broken with running at least `make index`.

2024-10-30 14:08 UTC, clausecker commented
@mat813 I have verified that `make index` is fine, as is a `poudriere bulk -an` dry-run (which should pick up any dangling dependencies).

2024-11-05 20:00 UTC, clausecker commented
Updated to just one squashed commit as requested.

Note that I'll likely have to rebase the patch set again before landing it, and that's much easier to do on the non-squashed patch set, so when landing, I will first rebase the unsquashed patch set and then squash it again before landing.

2024-11-05 20:01 UTC, dlangille commented
> Updated to just one squashed commit as requested.
> 
> Note that I'll likely have to rebase the patch set again before landing it, and that's much easier to do on the non-squashed patch set, so when landing, I will first rebase the unsquashed patch set and then squash it again before landing.

Do you have an ETA on landing please?

2024-11-05 20:04 UTC, clausecker commented
@dlangille I plan to land this one the instant I get portmgr approval.  There is nothing else left to do.

2024-11-06 10:28 UTC, rene0 commented
Approved with portmgr hat on

2024-11-06 15:03 UTC, clausecker commented
Will remove the following two ports from the patch set: funionfs, fusepak.  This is because they don't have `TIMESTAMP` in their `distinfo` and they don't fetch, so I can't regenerate `distinfo`.  Both are slated for removal, so I guess it's fine.

2024-11-06 15:21 UTC, clausecker commented
Closed by 6e2da9672f79f44048d597f0f61e4646cdeade9d.

2024-11-06 15:21 UTC, closed without merging

2024-11-13 00:36 UTC, bdrewery commented
I'm in a minority here but don't like this kind of moving chairs change.
- Some of us use "meta packages" that have RUN_DEPENDS on specific packages. Poudriere doesn't support MOVED there (no tool does). I'll consider adding support.
- Most ports reasonably could have multiple categories. What's a filesystem category that's not a sysutils? My port zfstools fits both. Are we nuking sysutils?
- "src-mgmt" is coming next, again every single tool going into there also fits in "devel", so what benefit is there?
- I don't see the motivation. What benefit does it bring? I used to be able to identity fusefs ports with `echo */*fusefs*` but now can't with that, so it's back to freshports or `git grep` anyway.
- POLA used to mean something. This kind of thing and renaming services `s/-/_/g` just creates downstream problems.

2024-12-27 10:56 UTC, grahamperrin commented
> I'm in a minority here but don't like this kind of moving chairs change.

> … Complainers don't always show up in a PR. This change hasn't even hit quarterly yet.

I'm not averse to change, however (in a future ideal world) there should be broader planning – including `src` (at least, manual pages), not forgetting Bugzilla and FreshPorts (its [bug-finder icon](https://www.freshports.org/faq.php#bugs-find)) – before move-related commits such as this.

That's an ideal world. I'm not complaining about reality :-)

Thanks

2025-01-06 07:14 UTC, grahamperrin commented
[283881 – Update documentation/ and website/ following moves of 142 ports to the filesystems category](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=283881)