Update /chinese/fcitx to 4.2.9.9 and update /chinese/libime to 1.1.9
freebsd/freebsd-ports pull request #322
Opened 2024-11-01 02:28 UTC by tempcracks

- [x] tested on 14.1-RELEASE

2024-11-01 02:46 UTC, lwhsu commented on chinese/fcitx/Makefile
> -PORTREVISION=	2
just remove `PORTREVISION` when `PORTVERSION` gets updated.

2024-11-01 02:46 UTC, lwhsu commented on chinese/libime/Makefile
> -PORTREVISION=	1
just remove `PORTREVISION` when `PORTVERSION` gets updated.

2024-11-01 02:47 UTC, lwhsu commented
@lichray

2024-11-01 02:48 UTC, lwhsu requested changes

2024-11-01 02:48 UTC, lwhsu commented on chinese/fcitx/Makefile
> +PORTREVISION=	3
just remove `PORTREVISION` when `PORTVERSION` gets updated.

2024-11-01 02:48 UTC, lwhsu commented on chinese/libime/Makefile
> +PORTREVISION=	2
just remove `PORTREVISION` when `PORTVERSION` gets updated.

2024-11-01 02:59 UTC, lichray commented on chinese/fcitx/Makefile
> +PORTREVISION=
Just delete the lines.

2024-11-01 03:01 UTC, tempcracks commented on chinese/fcitx/Makefile
> +PORTREVISION=
ok, sorry

2024-11-01 03:03 UTC, lichray approved these changes

2024-11-01 03:09 UTC, tempcracks commented
@lwhsu can you approve?

2024-11-01 03:51 UTC, lwhsu approved these changes

2024-11-01 03:51 UTC, lwhsu commented
Please help to split the updating of these 2 ports in 2 commits so it's easier for me to update metadata and push. Thanks.

2024-11-01 23:18 UTC, tempcracks commented
@lwhsu  everything's all right

2024-11-02 23:30 UTC, tempcracks commented
@lwhsu will you merge? Thank you

2024-11-04 14:28 UTC, lwhsu commented
> @lwhsu everything's all right?

Yes, thanks.

> @lwhsu will you merge? Thank you

Yes. I'll do some processing and merge. Please give me some more time.

2024-11-08 00:42 UTC, closed without merging